/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Wordament0AIDUEL;

import static java.lang.Thread.sleep;
import java.util.Set;

/**
 *
 *  Panel tempat permainan berlangsung
 */
public class JPanelMedanDuel extends javax.swing.JPanel {

    /**
     * Creates new form JPanelMedanDuel
     */
    public JPanelMedanDuel(AIPlayer _aip,char[][] _matchar, Set<String> _Kamus) {
        aip = _aip;
        matchar = _matchar;
        Kamus = _Kamus;
        initComponents();
    }
    
    public void bermain() throws InterruptedException{
        GameState HumanGameState = new GameState(matchar, Kamus);
        GameState AIGameState = new GameState(matchar, Kamus);
        
        GameLoop HumanGameLoop = new GameLoop(HumanGameState);
        GameLoop AIGameLoop = new GameLoop(AIGameState);
        
        Thread HPThread = new Thread(new HumanPlayer(HumanGameLoop,this));
        aip.setGame(AIGameLoop);
        Thread AIThread = new Thread(aip);
        
        Thread HPDispThread = new DisplayThread(HumanGameLoop,jPanelGameState1);
        Thread AIDispThread = new DisplayThread(AIGameLoop,jPanelGameState2);
        
        AIGameLoop.start();
        HumanGameLoop.start();
        HPDispThread.start();
        AIDispThread.start();
        HPThread.start();
        AIThread.start();
        
        //timer
        
        long now = System.currentTimeMillis();
        long start = now;
        while(now-start < 120000){
            if(System.currentTimeMillis()-now>=100){
                now=System.currentTimeMillis();
                jLabel3.setText("timeLeft: "+(120000-(now-start))+"ms");
            }
        }
        
        AIGameLoop.interrupt();
        HumanGameLoop.interrupt();
        HPDispThread.interrupt();
        AIDispThread.interrupt();
        HPThread.interrupt();
        AIThread.interrupt();
        
        AIGameLoop.join();
        HumanGameLoop.join();
        HPDispThread.join();
        AIDispThread.join();
        HPThread.join();
        AIThread.join();
        
        int humanscore = HumanGameState.totalScore();
        int AIscore = AIGameState.totalScore();
        if (humanscore<AIscore){
            jLabel3.setText("AI menang:\t" + humanscore + "-" + AIscore);
        }else if (humanscore==AIscore){
            jLabel3.setText("Seri:\t" + humanscore + "-" + AIscore);
            
        }else{
            jLabel3.setText("Manusia menang:\t" + humanscore + "-" + AIscore);
            
        }
    }
    
    private class DisplayThread extends Thread{
        GameLoop gl;
        JPanelGameState jpgs;
        public DisplayThread(GameLoop _gl, JPanelGameState _jpgs){
            gl = _gl; jpgs = _jpgs;
        }
        @Override
        public void run(){
            while (!isInterrupted()){
                PerintahGetGameState pggs = new PerintahGetGameState();
                gl.lakukanPerintah(pggs);
                try{
                    jpgs.displayGameState(pggs.getGS());
                    sleep(30);
                }catch(InterruptedException ie){
                    break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGameState1 = new com.Wordament0AIDUEL.JPanelGameState();
        jPanelGameState2 = new com.Wordament0AIDUEL.JPanelGameState();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Human");

        jLabel2.setText("AI");

        jLabel3.setText("timeLeft");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGameState1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelGameState2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGameState2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelGameState1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private AIPlayer aip;
    private char[][] matchar;
    private Set<String> Kamus;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.Wordament0AIDUEL.JPanelGameState jPanelGameState1;
    private com.Wordament0AIDUEL.JPanelGameState jPanelGameState2;
    // End of variables declaration//GEN-END:variables
}
