/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Wordament0AIDUEL;

import java.util.Iterator;
import java.util.NavigableSet;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.JLabel;

/**
 *
 * @author nim_13512501
 */
public class JPanelGameState extends javax.swing.JPanel {

    /**
     * Creates new form JPanelGameState
     */
    public JPanelGameState() {
        initComponents();
        initLabelsArray();
    }
    
    public void displayGameState(GameState gs){
        displayBoard(gs.GetBoard());
        displayKataTerbentuk(gs.getKataTerbentuk());
    }
    
    public void displayKataTerbentuk(SortedSet<Kata> kataTerbentuk){
        NavigableSet<Kata> kataTerbentukTmp = new TreeSet<Kata>(kataTerbentuk);
        String displayText = "";
        for (Iterator<Kata> it = kataTerbentukTmp.descendingIterator();it.hasNext();){
            Kata elem = it.next();
            displayText += elem.getScore() + "\t" + elem.getK() + "\n";
        }
        jTextArea1.setText(displayText);
    }
    
    public void displayBoard(Board b){
        for (int i=0;i<4;i++){
            for (int j=0;j<4;j++){
                String s = "";
                if (b.getVisited()[i][j])
                    s += "*";
                s+=b.getBoard()[i][j];
                labels[i][j].setText(s);
            }
        }
        JLabel pointedLabel = labels[b.getPointer().x][b.getPointer().y];
        pointedLabel.setText(pointedLabel.getText()+ "<");
    }
    
    private void initLabelsArray(){
        labels = new JLabel[4][4];
        labels[0][0]=jLabel1;
        labels[0][1]=jLabel2;
        labels[0][2]=jLabel3;
        labels[0][3]=jLabel4;
        labels[1][0]=jLabel5;
        labels[1][1]=jLabel6;
        labels[1][2]=jLabel7;
        labels[1][3]=jLabel8;
        labels[2][0]=jLabel9;
        labels[2][1]=jLabel10;
        labels[2][2]=jLabel11;
        labels[2][3]=jLabel12;
        labels[3][0]=jLabel13;
        labels[3][1]=jLabel14;
        labels[3][2]=jLabel15;
        labels[3][3]=jLabel16;
        
    }
    private JLabel[][] labels;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));
        jPanel1.add(jLabel1);
        jPanel1.add(jLabel2);
        jPanel1.add(jLabel3);
        jPanel1.add(jLabel4);
        jPanel1.add(jLabel5);
        jPanel1.add(jLabel6);
        jPanel1.add(jLabel7);
        jPanel1.add(jLabel8);
        jPanel1.add(jLabel9);
        jPanel1.add(jLabel10);
        jPanel1.add(jLabel11);
        jPanel1.add(jLabel12);
        jPanel1.add(jLabel13);
        jPanel1.add(jLabel14);
        jPanel1.add(jLabel15);
        jPanel1.add(jLabel16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
